---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

rac190a_demo_check:
  extends: .demo_check
  variables:
    server: ml-rac190a
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/cvuqdisk-1.0.10-1.rpm modules/software/files
    - cp ~/software/LINUX.X64_193000_grid_home.zip modules/software/files
    - cp ~/software/LINUX.X64_193000_db_home.zip modules/software/files
    - cp ~/software/p6880880_190000_Linux-x86-64.zip modules/software/files
    - cp ~/software/p30116789_190000_Linux-x86-64.zip modules/software/files

rac180a_demo_check:
  extends: .demo_check
  variables:
    server: ml-rac180a
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/cvuqdisk-1.0.10-1.rpm modules/software/files
    - cp ~/software/LINUX.X64_180000_grid_home.zip modules/software/files
    - cp ~/software/LINUX.X64_180000_db_home.zip modules/software/files
    - cp ~/software/p6880880_180000_Linux-x86-64.zip modules/software/files
    - cp ~/software/p30116795_180000_Linux-x86-64.zip modules/software/files

rac122a_demo_check:
  extends: .demo_check
  variables:
    server: ml-rac122a
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/linuxx64_12201_grid_home.zip modules/software/files
    - cp ~/software/cvuqdisk-1.0.10-1.rpm modules/software/files
    - cp ~/software/linuxx64_12201_database.zip modules/software/files
    - cp ~/software/p6880880_122010_Linux-x86-64.zip modules/software/files
    - cp ~/software/p29708720_122010_Linux-x86-64.zip modules/software/files

