---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

rac122a_demo_check:
  extends: .demo_check
  variables:
    server: ml-rac122a
  before_script:
    - mkdir -p modules/software/files
    - cp ~/software/linuxx64_12201_grid_home.zip modules/software/files
    - cp ~/software/linuxx64_12201_database.zip modules/software/files
    - cp ~/software/p6880880_121010_Linux-x86-64.zip modules/software/files
    - cp ~/software/p27468969_122010_Linux-x86-64.zip modules/software/files

